### PR TITLE
Initial implementation of driver

### LINKED ISSUE #1: T5838: initial general features and planned work
## Context

Multiple projects need a full-featured, Zephyr supported, T5838 driver.
 
This epic issue will list and track all relevant work connected to it. It is expected that the described work in it is broken into smaller issues, to make reviewing process easier.

## Required steps / Implementation details

* Prepare repository for driver development.
* Implement T5838 driver by using Zephyr's [dmic API](https://docs.zephyrproject.org/latest/hardware/peripherals/audio/dmic.html#c.dmic_trigger)
* Basic sampling sample - similar to this one: https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/audio/dmic
* On wake trigger sampling sample - Microphone is in low power, when increase in loudness is detected, the wake pin goes high, driver handles that, it samples for X seconds and then returns to low power.
* Wake, sample, got to sleep, repeat sample - Demonstrate that microphone can go to low power several times.

## Extra notes
 
**Most important thing**: Understand what microphone *modes* are and which ones are accessible to us when using Nordic chips. Use this [devzone issue](https://devzone.nordicsemi.com/f/nordic-q-a/15150/single-pdm-microphone-at-higher-pcm-sampling-rate) and chip's documentation as a starting point. Can we access all modes? If not, what do we lose with this?

- - -

Desirable configurable parameters:
* wakeup threshold
* band pass filter
* sampling interval
* mono/stereo mode (if this is too much effort then support only mono for now, no project needs stereo)

- - -

It is expected that Zephyr dmic API will not cover everything that this microphone does. Read [this](https://docs.zephyrproject.org/latest/kernel/drivers/index.html#device-specific-api-extensions) to learn how to expand the interface.

## Definition of Done

All above work is implemented, documented, tested and reviewed.

### PR DESCRIPTION
**Pull request by KajbaM**
## Description

This PR provides us with initial experimental implementation of T5838 driver.

Driver is based on existing zephyr NRF PDM driver and is to be used as mentioned driver replacement. Driver functionality should be identical to existing driver, but with added support for handling of T5838 AAD modes and custom PDM sampling frequency on both NRF52 and NRF53 series of chips (original driver does not allow us to use all desired pdm frequency options on nrf52).

Driver does support all T5838 AAD modes, but only AAD A mode was hardware tested (that is the mode we are most interested in). Other modes should work as well, but are not yet tested. See related issues to this PR for more information and concerns that should be addressed in further development of this driver.

Communication with microphone for setting AAD modes is done in bit-banging fashion, as microphone uses some kind of proprietary protocol for it. Replacing original driver was necessary since we need control of PDM CLK pin that is normally controlled by original driver and clock frequency should be configurable beyond what original driver supports on nrf52 platform.

Closes #1

Related #2 #3 #4 #5 #6 #7 #8

## Areas of interest for the reviewer

- `drivers/t5838/t5838_nrfx_pdm.c` - This is the main driver file, it is based on existing zephyr nrf pdm driver with added functionality to use AAD modes and allows us to set custom pdm sampling frequency on nrf52 chips (that is only possible with nrf53 with original driver).
- `drivers/t5838/t5838.h` - Header file for the drivers added functionality. Inside this file you can find added functionality for AAD modes, dmic compliant API is not changed and should work as with any zephyr compliant dmic implementation.
- `samples/dmic/` - This is modified zephyr dmic sample, it is modified to use T5838 driver instead of original nrf pdm driver. Please see `boards` subdirectory for example how device tree should be configured to use T5838 driver and `prj.conf` for required kconfig options.
- `README.md` - See repository README for more information about the driver and how to use it.

## Checklist

- [x] My code follows the [style guidelines] as defined by IRNAS.
- [x] I have performed a self-review of my code.
- [x] My changes generate no new warnings.
- [x] I added/updated source code documentation for all newly added or changed
      functions.
- [x] ~~I updated all customer-facing technical documentation.~~ - Does not yet exist/partially done.

## After-review steps

- I will merge PR by myself.

[style guidelines]:
  https://github.com/IRNAS/irnas-guidelines-docs/blob/main/docs/developer_guidelines.md

### CODE REVIEW

**Comment by KajbaM** [comment]
Current dependencies on/for this PR:
* main
  * **PR #9** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-t5838-driver/9" target="_blank">Graphite</a>  👈
    * **PR #11** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-t5838-driver/11" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/IRNAS/irnas-t5838-driver/9?utm_source=stack-comment).

File: drivers/t5838/t5838.h [hunk 1]
```diff
@@ -0,0 +1,226 @@
...
+#define T5838_H
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+#include <stdint.h>
+#include <zephyr/device.h>
+
+/* I will call their custom one wire thin FAKE2C because it is not really one wire */
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: I suggest you to write this comment not from the first person perspective, but something like: 

```
Although datasheet mentions that t5838 uses One Wire Protocol for configuration of AAD functionality, it is really using two wires (THSEL and CLK) for this, similar to the I2C protocol. That's why FAKE2C names was used to describe this protocol.
```
---
Another suggestion that you can implement: completely remove the comment and the FAKE2C naming from the defines. Other programmers do not lose any infromation if they see `T5838_START_PILOT_CLKS` instead of `T5838_FAKE2C_START_PILOT_CLKS` .

File: drivers/t5838/t5838.h [hunk 2]
```diff
@@ -0,0 +1,226 @@
...
+#define T5838_FAKE2C_SPACE	      1 * T5838_FAKE2C_START_PILOT_CLKS
+
+#define T5838_FAKE2C_POST_WRITE_CYCLES 60 /* According to datasheet >50clk cycles */
+#define T5838_FAKE2C_PRE_WRITE_CYCLES  60 /* According to datasheet >50clk cycles */
+#define T5838_FAKE2C_DEVICE_ADDRESS    0x53
+
+#define T5838_FAKE2C_CLK_PERIOD_US 10 /* approx 100kHz */
+
+#define T5838_ENTER_SLEEP_MODE_CLOCKING_TIME_uS                                                    \
+	2500 /* >2ms of clock is required before entering sleep with AAD  */
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: Move this comment above the define to prevent clang-format from wrapping it like that.

File: drivers/t5838/t5838.h [hunk 3]
```diff
@@ -0,0 +1,226 @@
...
+ * CLK = 0 - sleep mode with AAD active - supports AAD A and AAD D2  	|	PDM_OFF
+ * CLK 50-200kHz - sleep mode used for AAD configuration 		|	PDM_OFF?
+ * CLK 400-800kHz - low power mode with AAD D1 -  			|	PDM_ON
+ * CLK 2MHz-3,7MHz - High quality mode - no AAD 			|	PDM_ON
+ * CLK 4,2MHz-4,8MHz - ultrasonic mode - no AAD 			|	PDM_ON
+ *
+ * recomended for writing - 100kHz = 10us pulse width
+ */
+
+/**AAD ENABLE SEQUENCE - 0x5C/0x00 0x3E/0x00 0x6F/0x00 0x3B/0x00 0x4C/0x00*/
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: This section should be removed as it does not provide any value to the user of this driver.

File: drivers/t5838/t5838.h [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+ * @brief Pool AAD wake pin
+ *
+ * note that since T5838 does not have any interrupt flag logic, this is very unreliable way of
+ * reading AAD wake pin. Using interrupts is recommended.
+ *
+ * @param dev Pointer to the device structure for the driver instance.
+ *
+ * @return int 0 if successful, negative errno code if failure.
+ */
+int t5838_wake_get(const struct device *dev);
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: What does this function do? The doxygen comment does not describe the expected behavior, it only provides some internal logic explanation, also what is the function returning?

File: drivers/t5838/t5838.h [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+/**
+ * @brief Set AAD wake pin interrupt handler function
+ *
+ * Note that when interrupt gets triggered it will disable further interrupts until
+ * t5838_wake_clear() is called.
+ *
+ * @param dev Pointer to the device structure for the driver instance.
+ * @param handler Pointer to the handler function
+ */
+void t5838_wake_set_handler(const struct device *dev, T5838_wake_handler_t handler);
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: Provide some explanation under which conditions the given handler is called.

**Review by MarkoSagadin — CHANGES_REQUESTED** [review]
I have looked only through the t5838.h file. I have marked some specific things, however there are some general things that should be fixed in the entire file.

I didn't yet review yet the `t5838_nrfx_pdm.c` file. Because the original file (`dmic_nrfx_pdm.c`) was marked as deleted in the git and a new file was created as a copy, I don't see what were the new changes in the  `t5838_nrfx_pdm.c`  file. I just see the new file and I have to do the diff by myself (not really a great way to review stuff).

What you can do to fix that:
1. Soft reset the latest commit.
2. Store the contents of the t5838_nrfx_pdm.c somewhere.
3. Restore the old `dmic_nrfx_pdm.c` , so that I present in the directory as it was before.
4. Run `git mv dmic_nrfx_pdm.c t5838_nrfx_pdm.c`
5. Overwrite the contents with the previous backup and commit it.

That way the change will be presented correctly.

---
1. all enum, struct and function names should be lower case (as per our guidelines). Fix this in the header file and all files that use this.
2. All enums, struct should have a doxygen comment in below style:

```
/**
 * @brief Low pass filter frequency enums for AAD A mode.
 *
 * This settings are interesting for this and that reason, as described in the datasheet, on page XX, etc.
 */
```
If there are any things related to a specific enumerator or struct member you can write that in a comment above it.

3. A few times you start a doxygen comment with "note". You can use `@note` instead.
4. I would suggest you to remove t5838_wake_clear function. As discussed IRL, this can be implemented by the application. If multiple interrupt triggers are a concern than I suggest you to implement debounce timer logic. That way the application can still decide if it wants to use the debouncing or not.
5. I would suggest you to split the t5838_configure_AAD into several configure functions, for each AAD mode. Each function then takes a list of parameters (or a specific struct) it needs instead of passing in a config that contains everything.

Please reread the **source code documentation** and **doxygen guidelines** sections in our guidelines: https://github.com/IRNAS/irnas-guidelines-docs/blob/main/docs/developer_guidelines.md#coding-standards-
There is some form and general intent that should be followed regiarding the code documentation so that we are all on the same page about what some code does and that the time needed to understand that is minimized as much as possible.

File: drivers/t5838/t5838.h (hunk 1 above)
Comment (KajbaM) [reply drivers/t5838/t5838.h]: I think it is good idea we keep the FAKE2C naming, since this defines shouldn't really concern end user but can clear a lot of confusion since datasheet uses their incorrect one-wire naming for the protocol.

File: drivers/t5838/t5838.h (hunk 4 above)
Comment (KajbaM) [reply drivers/t5838/t5838.h]: That is mistake on my part. On the second thought I will actually just remove this function, since the way wake pin is driven will lead to unexpected behavior.

**Comment by KajbaM** [comment]
>     4. I would suggest you to remove t5838_wake_clear function. As discussed IRL, this can be implemented by the application. If multiple interrupt triggers are a concern than I suggest you to implement debounce timer logic. That way the application can still decide if it wants to use the debouncing or not.

I will first verify how interrupt triggering works with other modes of AAD operation before changing this. I will open up an issue regarding this and probably do some more and some other functionality and configuration to interrupt functionality to make it more versatile and also be more intuitive to use.

For now I would like to keep this functionality as is.

>     5. I would suggest you to split the t5838_configure_AAD into several configure functions, for each AAD mode. Each function then takes a list of parameters (or a specific struct) it needs instead of passing in a config that contains everything.

We could perhaps split this into one function for configuring AAD A and AAD D1/D2 combined (since they are practically same, one with pdm out and one without). I don't really see much benefit from doing this and feel like this might just introduce some confusion in case different modes get used at different points of time in same application.

User might think they can use AAD A and AAD D at the same time, which is not the case. Having same function for configuring both implies that selecting one mode in configuration will turn of the other.

File: drivers/t5838/t5838.h (hunk 1 above)
Comment (MarkoSagadin) [reply drivers/t5838/t5838.h]: Ok, agree. But then you should move them to the source file, as they are not expected to be used by the user (I forgot to mention this at the first review).

**Comment by MarkoSagadin** [comment]
@KajbaM 

> We could perhaps split this into one function for configuring AAD A and AAD D1/D2 combined (since they are practically same, one with pdm out and one without). 

This is actually the preferred solution. Different AAD modes require different sets of parameters. If the driver had several different AAD modes, but all of those would have the same configuration parameters, I would be OK with a single function (it would just take a single enum that represents a AAD mode and configuration struct, or even just the latter).

Since this is not the case here the cleaner interface is a separate function for each AAD mode. **Each function configures and enables that mode.** 

That way the configuration parameters are not contained in a single `cfg` struct, where user has to guess what is being used and what is redundant (_this is my biggest issue with the current interface design_).

> I don't really see much benefit from doing this and feel like this might just introduce some confusion in case different modes get used at different points of time in same application.

See below example API, I do not think that there is any confusion in regards to what mode is active (if D1 and D2 have the same exact parameters it might make sense to join them). 

```c
t5838_aad_a_mode_set(dev, &aad_a_cfg);
/*AAD A mode is active. */

t5838_aad_d1_mode_set(dev, &aad_d1_cfg);
/*AAD D1 mode is active. */

t5838_aad_d2_mode_set(dev, &aad_d2_cfg);
/*AAD D2 mode is active. */

t5838_aad_mode_disable(dev);
/*AAD is disable. */
```
> User might think they can use AAD A and AAD D at the same time, which is not the case. Having same function for configuring both implies that selecting one mode in configuration will turn of the other.

Again, not with the above example design.

File: README.md [hunk 6]
```diff
@@ -1,119 +1,180 @@
...
 
-```shell
-west init -m https://github.com/IRNAS/<repo-name> <repo-name>
-cd <repo-name>/project
+   ```yaml
+   - name: irnas-t5838-driver
+      repo-path: irnas-t5838-driver
+      path: irnas/irnas-t5838-driver
+      remote: irnas
+      revision: feature/t5838-driver
```
Comment (MarkoSagadin) [inline README.md]: Please leave this field deliberately empty, so that engineer has to manually select the version of the driver. That way don't have to update `revision` every time when we create a new release. 

Something like:

2. Then in the `projects` section add at the bottom (select the revision setting you need):
```
   - name: irnas-t5838-driver
      repo-path: irnas-t5838-driver
      path: irnas/irnas-t5838-driver
      remote: irnas
      revision: <revision>
```

Full disclosure: not all of our driver projects do this yet, this is something that should be addressed.

File: README.md [hunk 7]
```diff
@@ -1,119 +1,180 @@
...
+   #address-cells = < 0x1 >;
+   #size-cells = < 0x0 >;
+   ```
 
-```bash
-cd app
-east build -b <board_name> -u <build_type>
-```
+   This tells the kernel that the bus has 1 address cell and 0 size cells. So we don't have to set reg value to full address of the device, but only the address of the device on the bus. Note that reg property is not currently used, as we currently only support one device on the bus and microphone proprietary protocol (I refer to it as fake2c communication) address is hardcoded in the driver header file (0x53 which is the only address microphone supports).
+   It is planed reg value will be used in the future to support two microphones on the same bus (stereo configuration).
```
Comment (MarkoSagadin) [inline README.md:58]: Review this line, if it is correct, I don't fully understand it.

File: README.md [hunk 8]
```diff
@@ -1,119 +1,180 @@
...
+   ```
+
+   This will enable audio subsystem, dmic driver and disable nrfx pdm driver. We must disable nrfx default pdm driver, because it is not compatible with our driver. If you don't disable it, you will get a compile error.
+
+5. Don't forget to run `east clean` and `east update` before trying to build the project you are working on.
+
+## Usage
+
+The driver is used in the same way zephyr pdm driver is used. The only difference is that you need to use your microphones node name instead of `pdm0`. For example:
+
```
Comment (MarkoSagadin) [inline README.md]: Is something missing here, you write `For example:` but do not show anything?

File: README.md [hunk 9]
```diff
@@ -1,119 +1,180 @@
...
+Function for clearing interrupt is defined as follows:
+
+```c
+int t5838_wake_clear(const struct device *dev);
+```
+
+This function clears wake interrupt and reenables it. It is used to reenable wake interrupt after it has been triggered.
+
+Function for getting wake pin state is defined as follows:
```
Comment (MarkoSagadin) [inline README.md]: Everything in **AAD API** section is redundant. You already describe everything in the header file. It is much better to have a single point of truth of documentation than two.

**Review by MarkoSagadin — CHANGES_REQUESTED** [review]
Went through the documentation part, still didn't get to the source code.

File: drivers/t5838/CMakeLists.txt [hunk 10]
```diff
@@ -0,0 +1,8 @@
+# SPDX-License-Identifier: Apache-2.0
+
+if(CONFIG_T5838)
+    zephyr_include_directories(.)
+    zephyr_library()
+
+    zephyr_library_sources(t5838_nrfx_pdm.c)
+endif()
```
Comment (MarkoSagadin) [inline drivers/t5838/CMakeLists.txt]: This if statement is redundant, due to the `add_subdirectory_ifdef` line in the parent `CMakeLists.txt` file, remove it.

File: drivers/t5838/t5838.h [hunk 11]
```diff
@@ -0,0 +1,252 @@
...
+	T5838_AAD_A_THR_95dB = 0x0E,
+	T5838_AAD_A_THR_97_5dB = 0x0F
+};
+
+/**
+ * @brief AAD D mode absolute threshold
+ *
+ * This setting selects absolute threshold for AAD D mode.
+ * datasheet claim values between 0x00F and 0x7BC are allowed, but only provides us with table of
+ * discrete values defined in this enumerator
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: Add `@note` to this line, capitalize it and add period dot at the end. Repeat this in below docstrings, where you copied this sentence to.

File: drivers/t5838/t5838.h [hunk 12]
```diff
@@ -0,0 +1,277 @@
...
+ * @brief Set AAD wake pin interrupt handler function
+ *
+ * Function will set handler function to be called when interrupt is triggered. We can set handler
+ * at any time, but t5838_configure_AAD() must be called for interrupt triggering to be enabled.
+ *
+ * @note when interrupt gets triggered it will disable further interrupts until
+ * t5838_wake_clear() is called.
+ *
+ * @param dev Pointer to the device structure for the driver instance.
+ * @param handler Pointer to the handler function to be called when interrupt is triggered.
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: You are missing `[in]` marker at the end of the `@param`. Refer to the Nordic's [Doxygen guidelines](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/documentation/styleguide.html#doxygen-gl) that we follow, to learn how is this done.


Correct this in this header file and in any function that you added in the `t5838_nrfx_pdm.c` file.

File: drivers/t5838/t5838.h [hunk 13]
```diff
@@ -0,0 +1,277 @@
...
+ */
+void t5838_wake_handler_set(const struct device *dev, t5838_wake_handler_t handler);
+
+/**
+ * @brief Clear AAD wake pin interrupt and re-enable AAD interrupts.
+ *
+ * @param dev Pointer to the device structure for the driver instance.
+ *
+ * @return int 0 if successful, negative errno code if failure.
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h]: I think I have mentioned this in the IRL: for return values such as this use `@retval`, for example:

```
 * @retval 0                      If the operation was successful.
 * @retval negative error code    If otherwise.
 ```
 
Correct this in this header file and in any function that you added in the `t5838_nrfx_pdm.c` file.

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 14]
```diff
@@ -35,8 +76,473 @@ struct t5838_drv_cfg {
...
+	/** Make sure there is no PDM transfer in progress, and we can take clock signal */
+	if (drv_data->active) {
+		LOG_ERR("Cannot write to device while pdm is active");
+		return -EBUSY;
+	}
+
+	/**prepare data */
+	uint8_t wr_buf[] = {T5838_FAKE2C_DEVICE_ADDRESS << 1, reg, data
+
+	};
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: Put this on a single line

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 15]
```diff
@@ -360,29 +405,16 @@ int prv_t5838_aad_unlock_sequence(const struct device *dev)
 
 	if (drv_data->aad_unlocked == false) {
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: What is supporting evidence that unlock sequence needs to done only once?

I went through the datasheet and I see that there is no "aad lock" sequence being mentioned and it doesn't explicitly state that you should unlock it once, or every time you talk to the mic.

Can you check this with the microphone vendor?

It could be that is just safer to reset the mic everytime before user wants to configure it, it that case `aad_unlocked` would be redundant.

File: samples/dmic/boards/nrf52840dk_nrf52840.overlay [hunk 16]
```diff
@@ -0,0 +1,32 @@
...
+	clock-source = "PCLK32M_HFXO";
+	#address-cells = < 0x1 >;
+	#size-cells = < 0x0 >;
+	t5838: t5838@53 {
+		status = "okay";
+		compatible = "tdk,t5838-nrf-pdm";
+		micen-gpios = <&gpio1 11 GPIO_ACTIVE_HIGH>;
+		thsel-gpios = <&gpio1 4 GPIO_ACTIVE_HIGH>;
+		wake-gpios = <&gpio1 10 GPIO_ACTIVE_HIGH>;
+		pdmclk-gpios = <&gpio1 13 GPIO_ACTIVE_HIGH>;
```
Comment (MarkoSagadin) [inline samples/dmic/boards/nrf52840dk_nrf52840.overlay:28]: `pdmclk-gpios` is not correctly set, shouldn't be the same as the `PDM_CLK`?

File: samples/dmic/boards/nrf5340dk_nrf5340_cpuapp.overlay [hunk 17]
```diff
@@ -0,0 +1,36 @@
...
+	clock-source = "PCLK32M_HFXO";
+	#address-cells = < 0x1 >;
+	#size-cells = < 0x0 >;
+	t5838: t5838@53 {
+		status = "okay";
+		compatible = "tdk,t5838-nrf-pdm";
+		micen-gpios = <&gpio1 11 GPIO_ACTIVE_HIGH>;
+		thsel-gpios = <&gpio1 4 GPIO_ACTIVE_HIGH>;
+		wake-gpios = <&gpio1 10 GPIO_ACTIVE_HIGH>;
+		pdmclk-gpios = <&gpio1 13 GPIO_ACTIVE_HIGH>;
```
Comment (MarkoSagadin) [inline samples/dmic/boards/nrf5340dk_nrf5340_cpuapp.overlay:32]: `pdmclk-gpios` is not correctly set, shouldn't be the same as the `PDM_CLK`?

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 18]
```diff
@@ -0,0 +1,1310 @@
...
+#endif /**T5838_ANY_INST_AAD_CAPABLE */
+	/* Wait for device to power down and reapply power to reset it */
+	k_sleep(K_MSEC(T5838_RESET_TIME_MS));
+	err = gpio_pin_set_dt(drv_cfg->micen, 1);
+	if (err < 0) {
+		if (err < 0) {
+			LOG_ERR("gpio_pin_set_dt, err: %d", err);
+			return err;
+		}
+	}
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: Remove double if statements.

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 19]
```diff
@@ -0,0 +1,1310 @@
...
+	err = gpio_pin_set_dt(drv_cfg->micen, 0);
+	if (err < 0) {
+		if (err < 0) {
+			LOG_ERR("gpio_pin_set_dt, err: %d", err);
+			return err;
+		}
+	}
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: Remove double if statements.

File: drivers/t5838/t5838_nrfx_pdm.c
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c:1]: General remarks:

1. Replace `sizeof(write_data) / sizeof(write_data[0])`  with `ARRAY_SIZE` macro from `zephyr/sys/util.h` Do this anywhere where you are calculating the number of elements in array at compile time).
2. Remove `t5838` from static functions. For example: `prv_t5838_aad_unlock_sequence` becomes `prv_aad_unlock_sequence`. Reasoning: those functions can be used only inside this source file, so any extra info about the namespace is not needed.
3.  Regarding the newly added `struct t5838_address_data_pair` and its usage: you don't need to write `.address` and `.data` every time. Below example works and is more readable:
```C
struct t5838_address_data_pair write_data[] = {
        {0x5C, 0x00}, {0x3E, 0x00}, {0x6F, .0x00}, {0x3B, 0x00}, {0x4C, 0x00},
};
```
Change this in every place you use `t5838_address_data_pair`.
4.  Below `for` loop logic appears many times:
```C
for (int k = 0; k < SOME_NUMBER_OF_CYCLES; k++) {
	err = gpio_pin_set_dt(drv_cfg->pdmclk, 1);
	if (err < 0) {
		LOG_ERR("gpio_pin_set_dt, err: %d", err);
		return err;
	}
	k_busy_wait(T5838_FAKE2C_CLK_PERIOD_US / 2);
	err = gpio_pin_set_dt(drv_cfg->pdmclk, 0);
	if (err < 0) {
		LOG_ERR("gpio_pin_set_dt, err: %d", err);
		return err;
	}
	k_busy_wait(T5838_FAKE2C_CLK_PERIOD_US / 2);
}
```

Change this into a function that takes number of cycles as a parameter. 

5. Functions `t5838_aad_a_mode_set`, `t5838_aad_d1_mode_set` and `t5838_aad_d2_mode_set` only differ by the `addres_data` pairs that need to be written. Everything else before that and after that is the same. Refactor the common parts into a single static function and make each of the above functions to only call that function.

6.  Resolve the `T5838_ANY_INST_AAD_CAPABLE` and `-ENOSUP` ifdef pattern and "any pins are optional" problem. There is much cleaner way to do this: with `T5838_AAD_MODE` Kconfig option. 
Description of the behaviour:
* user needs to explicitly enable this.
* public AAD functions (definitions and declarations) are conditionally compiled if this option is enabled. There is no need to handle `-ENOSUP` at run time, people would get compile time error, if they tried to use any AAD related-function.
* If enabled, user **MUST** provide `thsel`, `wake` and `pdmclk` pins in the DTS. This means that the conditional logic in the `T5838_PDM_NRFX_DEVICE` related to the pins (`IF_ENABLED(T5838_HAS_MICEN_GPIO(idx)....`) can be simplified.
* It would be quite nice if the AAD functions would be in a separate `t5838_aad_mode.c` file, however since you already tried this and didn't succeed, this can be skipped.
* This means that `T5838_ANY_INST_HAS_WAKE`, `T5838_ANY_INST_HAS_THSEL`, `T5838_ANY_INST_HAS_PDM` and any similar defines can be removed.

Do this :arrow_up: .

7. Do not error handle `gpio_pin_*` functions all over the driver. Validate that `gpio` devices are functional in the `t5838_pdm_nrfx_init##idx` function, configure them if you have to and that's it. There is no need to error gpio functions, once you validated that they are initialized.

8. Do not call `prv_t5838_configure_gpios` in `t5838_configure` function and in `t5838_aad_mode_X_set`  functions. Call it once in the `t5838_pdm_nrfx_init##idx` function and only reconfigure what you must (`pdmclk` seems like a thing that you should always reconfigure, although I am not sure).

9. Some error messages do not match the function, for example see line 679. There are more.

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 20]
```diff
@@ -496,53 +1012,87 @@ static void init_clock_manager(const struct device *dev)
...
+#define T5838_WAKE_GPIO_SPEC(idx)                                                                  \
+	IF_ENABLED(T5838_HAS_WAKE_GPIO(idx),                                                       \
+		   (static const struct gpio_dt_spec wake_##idx =                                  \
+			    GPIO_DT_SPEC_GET(DT_DRV_INST(idx), wake_gpios);))
+
+#define T5838_HAS_PDMCLK_GPIO(idx) DT_NODE_HAS_PROP(DT_DRV_INST(idx), pdmclk_gpios)
+#define T5838_PDMCLK_GPIO_SPEC(idx)                                                                \
+	IF_ENABLED(T5838_HAS_PDMCLK_GPIO(idx),                                                     \
+		   (static const struct gpio_dt_spec pdmclk_##idx =                                \
+			    GPIO_DT_SPEC_GET(DT_DRV_INST(idx), pdmclk_gpios);))
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: Why are this `gpio_dt_spec` pins declared here and then passed as pointers to the configuration struct?

Remove this and assign them directly.

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 21]
```diff
@@ -4,15 +4,45 @@
...
+
+#ifdef CONFIG_AUDIO_DMIC_NRFX_PDM
+BUILD_ASSERT(CONFIG_AUDIO_DMIC_NRFX_PDM == 0,
+	     "Both T5838 and nrfx_pdm drivers enabled, set "
+	     "CONFIG_AUDIO_DMIC_NRFX_PDM to false to use T5838 driver");
+#endif
+
+#define DT_DRV_COMPAT tdk_t5838_nrf_pdm
+
+const struct device *gpio_dev = DEVICE_DT_GET(DT_NODELABEL(gpio1));
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: This is not doing anything, remove it.

**Review by MarkoSagadin — CHANGES_REQUESTED** [review]
Requested quite a few things. Please make them.

Also remove the `lib` and `renode_example` folders.

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 15 above)
Comment (KajbaM) [reply drivers/t5838/t5838_nrfx_pdm.c]: After powering microphone up, certain sequence needs to be written to enable use of AAD modes. This has to be done every time we want to use AAD after power cycling microphone. 

see section "5.12. AAD ENABLE SEQUENCE" of microphone datasheet.

Naming it "unlocked" was done to prevent confusion with just enabling AAD mode.

Comment (MarkoSagadin) [reply drivers/t5838/t5838_nrfx_pdm.c]: > see section "5.12. AAD ENABLE SEQUENCE" of microphone datasheet.

I missed out this section, so some of my previous comments can be dismissed (most notably my first question).

> It could be that is just safer to reset the mic everytime before user wants to configure it, it that case aad_unlocked would be redundant.

This comment is also wrong, `micen` is optional, so driver should not rely on it.

Copied from the datasheet:
> After this sequence has been completed any of the configuration settings for the AAD Analog or AAD Digital modes can be adjusted. The enable sequence can be written once to the microphone and will remain valid as long as power is maintained to the microphone. If the mic goes through a power cycle, then the sequence will have to be
repeated. 

I suggest you to implement it like that, run the unlock sequence once in the init (if AAD is enabled) or in `t5838_reset` (if AAD is enabled).

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 20 above)
Comment (KajbaM) [reply drivers/t5838/t5838_nrfx_pdm.c]: I did so since same implementation was done in our en25 driver, which I was looking at as an example of implementation. Will change

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 15 above)
Comment (KajbaM) [reply drivers/t5838/t5838_nrfx_pdm.c]: The issue with running said sequence once during init is that PDM functionality doesn't call init function when zephyr boots like with most zephyr drivers.

API is made in the way that you configure PDM peripheral parameters and call `dmic_configure()` to apply configuration to PDM peripheral.

However, I don't think it is good idea to depend on calling this function as initializer for AAD triggering functionality, since that prevents us from using AAD mode without having configured PDM peripheral. This limits potential use case where we can use AAD for triggering microphone levels but we don't need to actually sample PDM samples.

PDM configuration function is also not good place to do this, since changing PDM sampling rate during runtime does call configuration function multiple times to reapply new configuration. So we would need something to check if we already unlocked AAD modes anyway inside said function.

File: README.md (hunk 7 above)
Comment (KajbaM) [reply README.md:58]: I do need to further review this, the thing about these two DT parameters is that DTS expects full 4byte reg value if we don't set that for any sub peripheral. I will look further into this.

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 15 above)
Comment (MarkoSagadin) [reply drivers/t5838/t5838_nrfx_pdm.c]: > I suggest you to implement it like that, run the unlock sequence once in the init (if AAD is enabled) or in t5838_reset (if AAD is enabled).

To elaborate my previous statement: I meant `int t5838_pdm_nrfx_init##idx(const struct device *dev)` function, not `dmic_configure`.

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 20 above)
Comment (MarkoSagadin) [reply drivers/t5838/t5838_nrfx_pdm.c]: See similar implementation in our `irnas-notecard-driver`, more specifically: https://github.com/IRNAS/irnas-notecard-driver/blob/7a540a89e2044a6f5fc775b913fe8375aa23644d/drivers/notecard/notecard.c#L317C4-L317C20

File: drivers/t5838/t5838.h [hunk 22]
```diff
@@ -14,7 +14,11 @@ extern "C" {
 #endif
 
 #include <stdint.h>
-#include <zephyr/device.h>
+
+#include <nrfx_pdm.h>
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838.h:19]: Please check our include ordering in our guidelines: https://github.com/IRNAS/irnas-guidelines-docs/blob/main/docs/developer_guidelines.md#include-statements

`nrfx_pmd.h` should be placed after Zephyr includes.

File: drivers/t5838/t5838.h (hunk 13 above)
Comment (MarkoSagadin) [reply drivers/t5838/t5838.h]: @KajbaM This is still left to do.

File: drivers/t5838/t5838_aad_mode.c [hunk 23]
```diff
@@ -0,0 +1,486 @@
...
+#define T5838_ENTER_SLEEP_MODE_CLK_PERIOD_uS	10 /* approx 100kHz */
+
+#define T5838_RESET_TIME_MS 10 /* Time required for device to reset when power is disabled*/
+
+struct t5838_address_data_pair {
+	uint8_t address;
+	uint8_t data;
+};
+
+void prv_clock_bitbang(const struct device *dev, uint16_t cycles, uint16_t period)
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c:53]: Add a doxygen comment here.

File: drivers/t5838/t5838_aad_mode.c [hunk 24]
```diff
@@ -0,0 +1,486 @@
...
+	gpio_pin_set_dt(&drv_cfg->thsel, 1);
+	prv_clock_bitbang(dev, T5838_FAKE2C_STOP, T5838_FAKE2C_CLK_PERIOD_US);
+	gpio_pin_set_dt(&drv_cfg->thsel, 0);
+
+	/**keep clock to apply */
+	prv_clock_bitbang(dev, T5838_FAKE2C_POST_WRITE_CYCLES, T5838_FAKE2C_CLK_PERIOD_US);
+	return 0;
+}
+
+int prv_multi_reg_write(const struct device *dev, struct t5838_address_data_pair *data, uint8_t num)
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c:141]: Add doxygen comment here.

File: drivers/t5838/t5838_aad_mode.c [hunk 25]
```diff
@@ -0,0 +1,486 @@
...
+	}
+	return 0;
+}
+
+/**
+ * @brief Function helper for sending predefined sequence that unlocks aad mode.
+ *
+ * @param[in] dev Pointer to the device structure for the driver instance.
+ *
+ * @retval 0 If successful.
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: Write what is returned if function is not successful.

File: drivers/t5838/t5838_aad_mode.c [hunk 26]
```diff
@@ -0,0 +1,486 @@
...
+ */
+int prv_enter_sleep_with_AAD(const struct device *dev)
+{
+	prv_clock_bitbang(
+		dev, T5838_ENTER_SLEEP_MODE_CLOCKING_TIME_uS / T5838_ENTER_SLEEP_MODE_CLK_PERIOD_uS,
+		T5838_ENTER_SLEEP_MODE_CLK_PERIOD_uS);
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: Just noticed this: all macros (and enums) should be uppercase, regardless if they contain units. So `_uS` -> `_US`.

File: drivers/t5838/t5838_aad_mode.c [hunk 27]
```diff
@@ -0,0 +1,486 @@
...
+	}
+}
+
+int t5838_reset(const struct device *dev)
+{
+
+	const struct t5838_aad_drv_cfg *drv_cfg = dev->config;
+	struct t5838_aad_drv_data *drv_data = dev->data;
+	int err;
+	if (drv_cfg->micen_available) {
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: Revert the condition in the `if` statement, this will make the code after it more readable plus you will remove one level of indentation that is not needed.

```C
if (!drv_cfg->micen_available) {
    return -ENOTSUP;
}
```

File: drivers/t5838/t5838_aad_mode.c [hunk 28]
```diff
@@ -0,0 +1,486 @@
...
+
+		/* Wait for device to power down and reapply power to reset it */
+		k_sleep(K_MSEC(T5838_RESET_TIME_MS));
+		err = gpio_pin_set_dt(&drv_cfg->micen, 1);
+		if (err < 0) {
+			LOG_ERR("gpio_pin_set_dt, err: %d", err);
+			return err;
+		}
+		return 0;
+	}
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: Remove error handling for `gpio` functions.

File: drivers/t5838/t5838_aad_mode.c [hunk 29]
```diff
@@ -0,0 +1,486 @@
...
+	return -ENOTSUP;
+}
+
+int t5838_aad_wake_clear(const struct device *dev)
+{
+	const struct t5838_aad_drv_cfg *drv_cfg = dev->config;
+	struct t5838_aad_drv_data *drv_data = dev->data;
+	int err;
+	if (drv_data->cb_configured) {
+		err = gpio_pin_interrupt_configure_dt(&drv_cfg->wake, GPIO_INT_EDGE_TO_ACTIVE);
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: I only noticed this now: `GPIO_INT_EDGE_TO_ACTIVE` is power hungry, as the high frequency clock needs to be enabled for edge detection to work. In the past we have solved this by using the `GPIO_INT_ACTIVE_HIGH` (I might have used the wrong name) and reconfigured the interrupt in the in the ISR. Check the notecard driver to see how this is done for example.

I don't remember the exact additional uA that are added due to this, check with @TjazVracko, but is probably small compared to the ~20uA that are added due to the AAD feature. 

You don't have to do this, I am just bringing this to your attention. But definitely open an issue for this, so that we don't forget.

File: drivers/t5838/t5838_aad_mode.c [hunk 30]
```diff
@@ -0,0 +1,486 @@
...
+	if (err < 0) {
+		LOG_ERR("prv_t5838_multi_reg_write, err: %d", err);
+		return err;
+	}
+
+	err = prv_enter_sleep_with_AAD(dev);
+	if (err < 0) {
+		LOG_ERR("prv_t5838_reg_write, err: %d", err);
+		return err;
+	}
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: This always returns 0. I suggest you to remove the error handling and change the return type of the `prv_enter_sleep_with_AAD` to `void`.

File: drivers/t5838/t5838_aad_mode.c [hunk 31]
```diff
@@ -0,0 +1,486 @@
...
+		dev, T5838_ENTER_SLEEP_MODE_CLOCKING_TIME_uS / T5838_ENTER_SLEEP_MODE_CLK_PERIOD_uS,
+		T5838_ENTER_SLEEP_MODE_CLK_PERIOD_uS);
+	return 0;
+}
+
+/** this are here because we need to access device struct from callback handler which uses different
+ * device context */
+const struct t5838_aad_drv_cfg *g_drv_cfg = NULL;
+struct t5838_aad_drv_data *g_drv_data = NULL;
+static void prv_wake_cb_handler(const struct device *dev, struct gpio_callback *cb, uint32_t pins)
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: This is actually not needed, `CONTAINER_OF` should be used here. Check the https://github.com/IRNAS/irnas-notecard-driver/blob/7a540a89e2044a6f5fc775b913fe8375aa23644d/drivers/notecard/notecard.c#L114C4-L114C4

Comment (MarkoSagadin) [reply drivers/t5838/t5838_aad_mode.c]: If you decide not to implement this like that, atleast make the variable static and prepend them with `prv_` instead of `g_`.

Comment (MarkoSagadin) [reply drivers/t5838/t5838_aad_mode.c]: Reason: `prv_` are using for variables that are scoped to the translation unit (c file) where are they declared, `g_` is used for variables which scope contains multiple translation units.

File: drivers/t5838/t5838_aad_mode.c [hunk 32]
```diff
@@ -0,0 +1,486 @@
...
+		{T5838_REG_AAD_D_REL_PULSE_MIN_LO, aadconf->aad_d_rel_pulse_min & 0xFF},
+		{T5838_REG_AAD_D_ABS_REL_PULSE_MIN_SHARED,
+		 ((aadconf->aad_d_abs_pulse_min >> 4) / 0xF0) |
+			 ((aadconf->aad_d_rel_pulse_min >> 8) & 0x0F)},
+		{T5838_REG_AAD_D_ABS_PULSE_MIN_LO, aadconf->aad_d_abs_pulse_min & 0xFF},
+		{T5838_REG_AAD_D_ABS_THR_LO, aadconf->aad_d_abs_thr & 0xFF},
+		{T5838_REG_AAD_D_ABS_THR_HI, (aadconf->aad_d_abs_thr >> 8) & 0x1F},
+		{T5838_REG_AAD_D_REL_THR, aadconf->aad_d_rel_thr},
+		{T5838_REG_AAD_MODE, T5838_AAD_SELECT_D1},
+	};
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: Since a very similar table appears below, I would _suggest_ you to create a "builder" function that accepts `struct aad_d_conf`, which mode should be configured (D1, D2) and returns a pointer to this table (and it's length).

File: drivers/t5838/t5838_aad_mode.c [hunk 33]
```diff
@@ -0,0 +1,486 @@
...
+	drv_data->aad_enabled_mode = T5838_AAD_SELECT_NONE;
+	pdm_data->aad_child_dev = NULL;
+	return 0;
+}
+
+/**
+ * @brief Function for initializing T5838 AAD trigger device. Called during device boot.
+ *
+ * @param[in] dev Pointer to the device structure for the driver instance.
+ */
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c:411]: Add missing `@return`

File: drivers/t5838/t5838_aad_mode.c [hunk 34]
```diff
@@ -0,0 +1,486 @@
...
+static int t5838_aad_init(const struct device *dev)
+{
+	const struct t5838_aad_drv_cfg *drv_cfg = dev->config;
+	int err;
+	/* T5838 specific configuration */
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c:417]: delete this comment

File: drivers/t5838/t5838_aad_mode.c [hunk 35]
```diff
@@ -0,0 +1,486 @@
...
+
+	err = gpio_pin_configure_dt(&drv_cfg->wake, GPIO_INPUT);
+	if (err < 0) {
+		if (err < 0) {
+			LOG_ERR("gpio_pin_configure_dt, err: %d", err);
+			return err;
+		}
+	}
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c]: What's up with the double `if` statements in this function? Remove them. :laughing:

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 36]
```diff
@@ -984,7 +199,7 @@ static int t5838_configure(const struct device *dev, struct dmic_cfg *config)
 	nrfx_pdm_config_t nrfx_cfg;
 	nrfx_err_t err;
 
-	prv_t5838_configure_gpios(dev);
+	// prv_configure_gpios(dev);
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: Remove this.

File: drivers/t5838/t5838_aad_mode.c [hunk 37]
```diff
@@ -0,0 +1,486 @@
...
+		LOG_ERR("error writing aad unlock sequence, err: %d", err);
+		return err;
+	}
+	return 0;
+}
+
+#define T5838_AAD_DEVICE(idx)                                                                      \
+	static struct t5838_aad_drv_data t5838_aad_data_##idx;                                     \
+	static const struct t5838_aad_drv_cfg t5838_aad_cfg##idx = {                               \
+		.pdm_dev = DEVICE_DT_GET(DT_NODELABEL(pdm0)),                                      \
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_aad_mode.c:451]: Should you be hard-coding `pdm0` here? There are devicetree macros that enable you to get the "bus" on which the child device is, is better to use that.

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 38]
```diff
@@ -1155,9 +374,12 @@ static int t5838_trigger(const struct device *dev, enum dmic_trigger cmd)
...
 			nrfx_pdm_stop();
 		}
-		if (drv_data->aad_enabled_mode != T5838_AAD_SELECT_NONE) {
-			prv_t5838_enter_sleep_with_AAD(dev);
+#ifdef CONFIG_T5838_AAD_TRIGGER
+
+		if (drv_data->aad_child_dev != NULL) {
+			prv_enter_sleep_with_AAD(drv_data->aad_child_dev);
 		}
+#endif
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: I am not sure, if I am satisfied with the fact that `aad_child_dev` is used to dynamically change. I my mind (and how Zephyr uses this) relationships between `struct device`s are compile time fixed, not dynamically changed at runtime. 

However I currently see no any other way of doing this with two separate devices (one for dmic, one for AAD). IMO, it would be better that, if this was one device, but since it is done like that than it can stay.

But please change the `prv_enter_sleep_with_AAD`. To me it looks like that you are creating an access to a private function from another module from thin air. Check how this is done in the `lis2dw12` driver: 
* Declarations of trigger related functions are ifdefed in the header file.
* functions are namespaced - in our case you need `t5838_aad_sleep` (noun->verb to be consistent with the rest)
* You call the function via ifdef, like you already do.

In that case the above forward declaration is redundant and can be removed.

**Review by MarkoSagadin — CHANGES_REQUESTED** [review]
Another pass was done, this looks much better now, good job :).
I marked a few things, please fix them. 

I also marked some of the things that weren't fixed from the previous review, it seems that they slipped through.
Please address the marked changes first, before doing any refactoring work or at least go through them before you re-request my review. 

It takes mental effort and time to go through my previous review and see if you addressed my feedback, either in code or with a comment.

File: drivers/t5838/t5838_aad_mode.c (hunk 29 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: Thank you for information, I was not aware of that and will look into it. I have to check/make sure stuff will work timing/consumption wise.

File: drivers/t5838/t5838_aad_mode.c (hunk 31 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: Thank you! I wasn't aware of this solution. And I agree current implementation is not the best. Will check and confirm this works with me.

File: drivers/t5838/t5838_aad_mode.c (hunk 32 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: Is this really necessary? I think we don't really gain much since all these 3 functions do now is build this sequence and pass it into another function that does configuration. I think it might just add unnecessary layer that won't really help with either readability or performance.

File: drivers/t5838/t5838_aad_mode.c (hunk 35 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: Arggghhh missed those again... Copilot wrote them and my brain just abstracts those out when reading code. :)

File: drivers/t5838/t5838_aad_mode.c (hunk 37 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c:451]: I can try using the bus functions, I am however not sure if they actually work with PDM (I did try at some point and had some problems, not sure what it was exactly). Hard-coding that is however not really a problem since nRF always has only one PDM that should always be labeled pdm0.

I will look into this, it shouldn't be introducing any problems however (except perhaps in case of porting this driver to another architecture where that is not the case).

File: drivers/t5838/t5838_nrfx_pdm.c (hunk 38 above)
Comment (KajbaM) [reply drivers/t5838/t5838_nrfx_pdm.c]: Yes, I was struggling to find better solution for this too, but also came to conclusion that this is the best solution possible.

My initial thoughts were also that triggering and PDM should be handled as one device, it was also initially implemented that way. 

I changed to implementation where trigger and PDM are separate with following in mind:
-by separating this into two devices, we can keep original driver in pretty much original/slightly modified state, making it easy to upgrade to further upstream version when original driver gets updates.

-Since there can be situation in the future where single PDM interface has two microphones on the bus implementing this as single device would REALLY complicate things. I know this is not needed now, but I just don't want to risk hitting this wall in the future if that is needed. Doing stuff that way is much more flexible and sensible when we count potential stereo configuration in the future.

-This is the only place where we actually need to access child device from parent and it is only done for convenience sake - it could be also implemented to be manually handled by the user. I think however, this gives us unnecessary point of failure when using driver. What this call does is that after sampling PDM it calls this function that provide microphone with 100kHz clock for some defined time which is needed for correctly setting device into its sleep mode. Not calling this function after sampling results in extra power consumption from the microphone, triggers still work however. Expecting user to manually call this after stopping PDM would probably result in situation where driver user would forget/not know they have to call this every time they stop PDM sampling and then wonder why their device draws more power than expected.


I was considering doing it the way it is done in `lis2dw12` but wasn't sure I should actually expose this function (yes it is ifdef-ed in header file there, but that doesn't really make it private). I am not exactly sure I want to do so, since the way driver is written now that function has no use for the user since it gets called by the driver when it is supposed to. Since this function was ifdef-ed here right above this trigger function I think it is obvious enough where it comes from, so not sure I would call that "from thin air".
I might just expose this function though, since it shouldn't really do any harm.

File: drivers/t5838/t5838_aad_mode.c (hunk 30 above)
Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: that is correct, but I think it should be done the other way around and check and make sure clock was not taken by PDM peripheral?

Comment (KajbaM) [reply drivers/t5838/t5838_aad_mode.c]: On the second thought, you are right. Since we are calling this immediately after disabling it, checking for active condition will fail since PDM event handler gets set later (which might not be best idea though).

File: drivers/t5838/t5838_nrfx_pdm.c [hunk 39]
```diff
@@ -28,7 +29,11 @@ BUILD_ASSERT(CONFIG_AUDIO_DMIC_NRFX_PDM == 0,
 
 static void free_buffer(struct t5838_drv_data *drv_data, void *buffer)
 {
+#if KERNELVERSION >= 0x3046300
+	k_mem_slab_free(drv_data->mem_slab, buffer);
+#else
 	k_mem_slab_free(drv_data->mem_slab, &buffer);
+#endif
```
Comment (MarkoSagadin) [inline drivers/t5838/t5838_nrfx_pdm.c]: We misunderstood each other: 
* use `sys_kernel_version_get` to get the kernel version
* use `SYS_KERNEL_VER_MAJOR` and `SYS_KERNEL_VER_MINOR` macros in a switch statement to determine which api to use.

**Review by MarkoSagadin — APPROVED** [review]
I approve this, very good job :)

I marked a minor thing, fix it and you can merge.
